addons:
  postgresql: 10.3

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.4.1
script:
  - bundle install
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rspec
