addons:
  postgresql: 9.6

dist: trusty

language: ruby

rvm:
  - 2.4.1

script:
  - bundle install
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake db:seed
  - bundle exec rspec
